films_data = [{'imdb_id': 'tt0120601',
  'title': 'Being John Malkovich',
  'year': 1999,
  'popularity': 1924,
  'description': "Puppeteer Craig Schwartz and animal lover and pet store clerk Lotte Schwartz are just going through the motions of their marriage. Despite not being able to earn a living solely through puppeteering, Craig loves his profession as it allows him to inhabit the skin of others. He begins to take the ability to inhabit the skin of others to the next level when he is forced to take a job as a file clerk for the off-kilter LesterCorp, located on the five-foot tall 7½ floor of a Manhattan office building. Behind one of the filing cabinets in his work area, Craig finds a hidden door which he learns is a portal into the mind of John Malkovich, the visit through the portal which lasts fifteen minutes after which the person is spit into a ditch next to the New Jersey Turnpike. Craig is fascinated by the meaning of life associated with this finding. Lotte's trips through the portal make her evaluate her own self. And the confident Maxine Lund, one of Craig's co-workers who he tells about the ...",
  'content_rating': 'R',
  'movie_length': 113,
  'rating': 7.7,
  'created_at': '2021-04-29T11:23:21.370614+03:00',
  'trailer': 'https://www.youtube.com/embed/2UuRFr0GnHM',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BYmUxY2MyOTQtYjRlMi00ZWEwLTkzODctZDMxNDcyNTFhYjNjXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-03-30',
  'plot': 'A puppeteer discovers a portal that leads literally into the head of movie star John Malkovich.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BYmUxY2MyOTQtYjRlMi00ZWEwLTkzODctZDMxNDcyNTFhYjNjXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 6, 'genre': 'Fantasy'},
   {'id': 8, 'genre': 'Drama'},
   {'id': 9, 'genre': 'Comedy'}],
  'keywords': [{'id': 1213, 'keyword': 'body swap'},
   {'id': 1289, 'keyword': 'portal'},
   {'id': 3279, 'keyword': 'magical realism'},
   {'id': 6390, 'keyword': 'puppeteer'},
   {'id': 6391, 'keyword': 'body switching'}]},
 {'imdb_id': 'tt0162661',
  'title': 'Sleepy Hollow',
  'year': 1999,
  'popularity': 1261,
  'description': 'The curse of The Headless Horseman (Christopher Walken) is the legacy of the small town of Sleepy Hollow. Spearheaded by the eager Constable Ichabod Crane (Johnny Depp) and his new world ways into the quagmire of secrets and murder, secrets once laid to rest, best forgotten and now reawakened, and he too, holding a dark secret of a past once gone.',
  'content_rating': 'R',
  'movie_length': 105,
  'rating': 7.3,
  'created_at': '2021-04-29T11:23:30.390955+03:00',
  'trailer': 'https://www.youtube.com/embed/6RsKwn_Je1k',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMTQ4Yjk5ODEtNGFkOS00OTY1LTgwYTYtOTFkNmU2NzBmNGM2XkEyXkFqcGdeQXVyNDQ2MTMzODA@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-04-06',
  'plot': 'Ichabod Crane is sent to Sleepy Hollow to investigate the decapitations of three people, with the culprit being the legendary apparition, The Headless Horseman.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BMTQ4Yjk5ODEtNGFkOS00OTY1LTgwYTYtOTFkNmU2NzBmNGM2XkEyXkFqcGdeQXVyNDQ2MTMzODA@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 6, 'genre': 'Fantasy'},
   {'id': 15, 'genre': 'Mystery'},
   {'id': 28, 'genre': 'Horror'}],
  'keywords': [{'id': 309, 'keyword': 'investigation'},
   {'id': 694, 'keyword': 'sword'},
   {'id': 1143, 'keyword': 'legend'},
   {'id': 4663, 'keyword': 'headless horseman'},
   {'id': 4664, 'keyword': 'beheading'}]},
 {'imdb_id': 'tt0151804',
  'title': 'Office Space',
  'year': 1999,
  'popularity': 816,
  'description': "In the Initech office, the insecure Peter Gibbons hates his job and the obnoxious Division VP Bill Lumbergh who has just hired two efficiency consultants to downsize the company. His best friends are two software engineers Michael Bolton and Samir Nagheenanajar, that also hate Initech, and his intrusive next door neighbor Lawrence. He believes his girlfriend Anne is cheating on him but she convinces Peter to visit the hypnotherapist Dr. Swanson. Peter tells how miserable his life is and Dr. Swanson hypnotizes him and he goes into a state of ecstasy. However, Dr. Swanson dies immediately after giving the hypnotic suggestion to Peter. Peter, in his new state, starts to date the waitress Joanna and changes his attitude which results in his being promoted by the consultants. When he discovers that Michael and Samir will be downsized, they decide to plant a virus in the banking system to embezzle fraction of cents on each financial operation into Peter's account. However Michael commits a ...",
  'content_rating': 'R',
  'movie_length': 89,
  'rating': 7.7,
  'created_at': '2021-04-29T11:23:39.074900+03:00',
  'trailer': '',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BOTA5MzQ3MzI1NV5BMl5BanBnXkFtZTgwNTcxNTYxMTE@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-06-10',
  'plot': 'Three company workers who hate their jobs decide to rebel against their greedy boss.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BOTA5MzQ3MzI1NV5BMl5BanBnXkFtZTgwNTcxNTYxMTE@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 9, 'genre': 'Comedy'}],
  'keywords': [{'id': 89, 'keyword': 'computer'},
   {'id': 284, 'keyword': 'black comedy'},
   {'id': 2549, 'keyword': 'boss'},
   {'id': 2552, 'keyword': 'office'},
   {'id': 2553, 'keyword': 'corporation'}]},
 {'imdb_id': 'tt0142342',
  'title': 'Big Daddy',
  'year': 1999,
  'popularity': 1490,
  'description': "Sonny Koufax is 32 years old. He's a law school graduate. He's got a nice apartment in Manhattan. There's just one problem. He does nothing, except sit on his butt and live off an investment that was the result of a meager lawsuit he won a year ago. But after his fed up girlfriend leaves him, he comes up with the ingenious idea to adopt a five year old boy to showcase his newfound maturity. But things don't go as planned, and Sonny finds himself the unlikely foster father that will change his perspective on just looking out for himself.",
  'content_rating': 'PG-13',
  'movie_length': 93,
  'rating': 6.4,
  'created_at': '2021-04-29T11:23:50.935243+03:00',
  'trailer': 'https://www.youtube.com/embed/jxnccxgybUI',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BYjAzNzQ4YzEtZWFlOS00YWVkLWE2NDctZDBiZTUxYjgwOTYzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-11-04',
  'plot': "A lazy law school grad adopts a kid to impress his girlfriend, but everything doesn't go as planned and he becomes the unlikely foster father.",
  'banner': 'https://m.media-amazon.com/images/M/MV5BYjAzNzQ4YzEtZWFlOS00YWVkLWE2NDctZDBiZTUxYjgwOTYzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'}, {'id': 9, 'genre': 'Comedy'}],
  'keywords': [{'id': 6, 'keyword': 'orphan'},
   {'id': 122, 'keyword': 'new york city'},
   {'id': 4795, 'keyword': 'responsibility'},
   {'id': 6990, 'keyword': 'homeless man'},
   {'id': 6991, 'keyword': 'immaturity'}]},
 {'imdb_id': 'tt0125439',
  'title': 'Notting Hill',
  'year': 1999,
  'popularity': 1063,
  'description': "Every man's dream comes true for William Thacker, an unsuccessful Notting Hill bookstore owner, when Anna Scott, the world's most beautiful woman and best-liked actress, enters his shop. A little later, he still can't believe it himself, William runs into her again - this time spilling orange juice over her. Anna accepts his offer to change in his nearby apartment, and thanks him with a kiss, which seems to surprise her even more than him. Eventually, Anna and William get to know each other better over the months, but being together with the world's most wanted woman is not easy - neither around your closest friends, nor in front of the all-devouring press.",
  'content_rating': 'PG-13',
  'movie_length': 124,
  'rating': 7.1,
  'created_at': '2021-04-29T11:23:54.202953+03:00',
  'trailer': 'https://www.youtube.com/embed/4RI0QvaGoiI',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMTE5OTkwYzYtNDhlNC00MzljLTk1YTktY2IxZjliZmNjMjUzL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-07-01',
  'plot': 'The life of a simple bookshop owner changes when he meets the most famous film star in the world.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BMTE5OTkwYzYtNDhlNC00MzljLTk1YTktY2IxZjliZmNjMjUzL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'},
   {'id': 9, 'genre': 'Comedy'},
   {'id': 26, 'genre': 'Romance'}],
  'keywords': [{'id': 121, 'keyword': 'hotel'},
   {'id': 245, 'keyword': 'friendship'},
   {'id': 1018, 'keyword': 'dating'},
   {'id': 2929, 'keyword': 'park'},
   {'id': 2930, 'keyword': 'fake reporter'}]},
 {'imdb_id': 'tt0134119',
  'title': 'The Talented Mr. Ripley',
  'year': 1999,
  'popularity': 1549,
  'description': "The 1950s. Manhattan lavatory attendant, Tom Ripley, borrows a Princeton jacket to play piano at a garden party. When the wealthy father of a recent Princeton grad chats Tom up, Tom pretends to know the son and is soon offered $1,000 to go to Italy to convince Dickie Greenleaf to return home. In Italy, Tom attaches himself to Dickie and to Marge, Dickie's cultured fiancée, pretending to love jazz and harboring homoerotic hopes as he soaks in luxury. Besides lying, Tom's talents include impressions and forgery, so when the handsome and confident Dickie tires of Tom, dismissing him as a bore, Tom goes to extreme lengths to make Greenleaf's privileges his own.",
  'content_rating': 'R',
  'movie_length': 139,
  'rating': 7.4,
  'created_at': '2021-04-29T11:24:07.815960+03:00',
  'trailer': 'https://www.youtube.com/embed/h4e-Si4oGEw',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BODA3NDhiZjYtYTk2NS00ZWYwLTljYTQtMjU0NzcyMGEzNTU2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-02-17',
  'plot': 'In late 1950s New York, Tom Ripley, a young underachiever, is sent to Italy to retrieve Dickie Greenleaf, a rich and spoiled millionaire playboy. But when the errand fails, Ripley takes extreme measures.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BODA3NDhiZjYtYTk2NS00ZWYwLTljYTQtMjU0NzcyMGEzNTU2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 7, 'genre': 'Crime'},
   {'id': 8, 'genre': 'Drama'},
   {'id': 14, 'genre': 'Thriller'}],
  'keywords': [{'id': 107, 'keyword': 'sociopath'},
   {'id': 503, 'keyword': 'male frontal nudity'},
   {'id': 664, 'keyword': 'italy'},
   {'id': 679, 'keyword': 'neo noir'},
   {'id': 1301, 'keyword': 'nudity'}]},
 {'imdb_id': 'tt0142688',
  'title': 'The Ninth Gate',
  'year': 1999,
  'popularity': 2335,
  'description': 'In New York, the money-driven dealer Dean Corso is a rare-books expert and partner of Bernie, who owns a bookstore. He is contacted by the renowned collector of books about the devil Boris Balkan, who has just acquired the rare The Nine Gates of the Kingdom of Shadows from the collector Andrew Telfer, to verify whether his book is authentic or a forgery. Balkan explains that the book was written by the writer Aristide Torchia, in 1666, with Lucifer and he was burned at the stake with his entire work. There are only three exemplars of The Nine Gates and in accordance with the legend, its nine engravings form a riddle to conjure the devil. The skeptical Corso accepts the assignment and has to fly to Sintra, Portugal, and Paris, France, to contact the owners Victor Fargas and Baroness Kessler and find the genuine exemplar for Balkan. Meanwhile, he asks Bernie to hide the rare book. Before traveling to Europe, the widow Liana Telfer wants to retrieve the book and has sex with Corso, but ...',
  'content_rating': 'R',
  'movie_length': 133,
  'rating': 6.7,
  'created_at': '2021-04-29T11:24:12.616023+03:00',
  'trailer': 'https://www.youtube.com/embed/IKc1n-nIIx0',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BM2Q1ZTFhMmYtNDljMS00Y2ZhLWE3M2QtMjYwYmFkYmJmMjI1XkEyXkFqcGdeQXVyNjU0NTI0Nw@@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-05-31',
  'plot': 'A rare book dealer, while seeking out the last two copies of a demon text, gets drawn into a conspiracy with supernatural overtones.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BM2Q1ZTFhMmYtNDljMS00Y2ZhLWE3M2QtMjYwYmFkYmJmMjI1XkEyXkFqcGdeQXVyNjU0NTI0Nw@@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 14, 'genre': 'Thriller'}, {'id': 15, 'genre': 'Mystery'}],
  'keywords': [{'id': 5475, 'keyword': 'rare book'},
   {'id': 5476, 'keyword': 'book detective'},
   {'id': 5477, 'keyword': 'bibliophilia'},
   {'id': 5478, 'keyword': 'satanic'},
   {'id': 5479, 'keyword': 'unholy book'}]},
 {'imdb_id': 'tt0171804',
  'title': "Boys Don't Cry",
  'year': 1999,
  'popularity': 2584,
  'description': "Based on actual events. Brandon Teena is the popular new guy in a tiny Nebraska town. He hangs out with the guys, drinking, cussing, and bumper surfing, and he charms the young women, who've never met a more sensitive and considerate young man. Life is good for Brandon, now that he's one of the guys and dating hometown beauty Lana; however, he's forgotten to mention one important detail. It's not that he's wanted in another town for GTA and other assorted crimes, but that Brandon Teena was actually born a woman named Teena Brandon. When his best friends make this discovery, Brandon's life is ripped apart.",
  'content_rating': 'R',
  'movie_length': 118,
  'rating': 7.5,
  'created_at': '2021-04-29T11:24:29.223771+03:00',
  'trailer': 'https://www.youtube.com/embed/Ar9wGSd7KVQ',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BN2YyODgyYjMtN2ZiZC00OWMzLTg1NjgtZGIwN2NlYTYxMTkwXkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-02-03',
  'plot': 'A young man named Brandon Teena navigates love, life, and being transgender in rural Nebraska.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BN2YyODgyYjMtN2ZiZC00OWMzLTg1NjgtZGIwN2NlYTYxMTkwXkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 7, 'genre': 'Crime'},
   {'id': 8, 'genre': 'Drama'},
   {'id': 26, 'genre': 'Romance'},
   {'id': 27, 'genre': 'Biography'}],
  'keywords': [{'id': 124, 'keyword': 'based on true story'},
   {'id': 796, 'keyword': 'sex'},
   {'id': 3915, 'keyword': 'transgender'},
   {'id': 5248, 'keyword': 'prejudice'},
   {'id': 7253, 'keyword': 'sexual assault'}]},
 {'imdb_id': 'tt0137523',
  'title': 'Fight Club',
  'year': 1999,
  'popularity': 171,
  'description': 'A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power.',
  'content_rating': 'R',
  'movie_length': 139,
  'rating': 8.8,
  'created_at': '2021-04-29T11:24:35.173860+03:00',
  'trailer': 'https://www.youtube.com/embed/qtRKdVHc-cE',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-11-04',
  'plot': 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'}],
  'keywords': [{'id': 702, 'keyword': 'surprise ending'},
   {'id': 770, 'keyword': 'multiple personality disorder'},
   {'id': 1123, 'keyword': 'fighting'},
   {'id': 1559, 'keyword': 'insomnia'},
   {'id': 1749, 'keyword': 'anti establishment'}]},
 {'imdb_id': 'tt0120689',
  'title': 'The Green Mile',
  'year': 1999,
  'popularity': 195,
  'description': "Death Row guards at a penitentiary, in the 1930's, have a moral dilemma with their job when they discover one of their prisoners, a convicted murderer, has a special gift.",
  'content_rating': 'R',
  'movie_length': 189,
  'rating': 8.6,
  'created_at': '2021-04-29T11:24:36.079441+03:00',
  'trailer': 'https://www.youtube.com/embed/Ki4haFrqSrw',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-02-10',
  'plot': 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 6, 'genre': 'Fantasy'},
   {'id': 7, 'genre': 'Crime'},
   {'id': 8, 'genre': 'Drama'},
   {'id': 15, 'genre': 'Mystery'}],
  'keywords': [{'id': 64, 'keyword': '1930s'},
   {'id': 1305, 'keyword': 'good versus evil'},
   {'id': 1545, 'keyword': 'death row inmate'},
   {'id': 1546, 'keyword': 'prison guard'},
   {'id': 1547, 'keyword': 'death row'}]},
 {'imdb_id': 'tt0139134',
  'title': 'Cruel Intentions',
  'year': 1999,
  'popularity': 747,
  'description': "Kathryn Merteuil and Sebastian Valmont are seductive, manipulative step-siblings who get what they want when they want it. Kathryn makes a bet with Sebastian: Sebastian must bed Annette, daughter of the headmaster at their school, before the end of summer break. Annette has stated that she would wait until love and marriage to sleep with a man. If Kathryn wins, she gets Sebastian's vintage 1959 Jaguar Roadster. If Sebastian wins, he gets Kathryn, the only girl he knows he'll never have. Also in play is Cecile, a naïve girl whose mother had enlisted Kathryn to help her fit in at her new school. However, Kathryn (with Sebastian's help) plans to ruin Cecile's reputation as revenge on Kat's ex-boyfriend, who left her for Cecile.",
  'content_rating': 'R',
  'movie_length': 97,
  'rating': 6.8,
  'created_at': '2021-04-29T11:24:38.602695+03:00',
  'trailer': 'https://www.youtube.com/embed/_ORVsGsn7_4',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMjMxNjM5OTQ2M15BMl5BanBnXkFtZTgwNjUxNzYxMTE@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-08-26',
  'plot': "Two vicious step-siblings of an elite Manhattan prep school make a wager: to deflower the new headmaster's daughter before the start of term.",
  'banner': 'https://m.media-amazon.com/images/M/MV5BMjMxNjM5OTQ2M15BMl5BanBnXkFtZTgwNjUxNzYxMTE@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'}, {'id': 26, 'genre': 'Romance'}],
  'keywords': [{'id': 1387, 'keyword': 'virgin'},
   {'id': 1414, 'keyword': 'seduction'},
   {'id': 1432, 'keyword': 'borderline personality disorder'},
   {'id': 1628, 'keyword': 'narcissism'},
   {'id': 2712, 'keyword': 'seductive woman'}]},
 {'imdb_id': 'tt0167404',
  'title': 'The Sixth Sense',
  'year': 1999,
  'popularity': 737,
  'description': 'Malcom Crowe (Bruce Willis) is a child psychologist who receives an award on the same night that he is visited by a very unhappy ex-patient. After this encounter, Crowe takes on the task of curing a young boy with the same ills as the ex-patient (Donnie Wahlberg) . This boy "sees dead people". Crowe spends a lot of time with the boy much to the dismay of his wife (Olivia Williams). Cole\'s mom (Toni Collette) is at her wit\'s end with what to do about her son\'s increasing problems. Crowe is the boy\'s only hope.',
  'content_rating': 'PG-13',
  'movie_length': 107,
  'rating': 8.1,
  'created_at': '2021-04-29T11:24:39.476361+03:00',
  'trailer': 'https://www.youtube.com/embed/3-ZP95NF_Wk',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMWM4NTFhYjctNzUyNi00NGMwLTk3NTYtMDIyNTZmMzRlYmQyXkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-12-30',
  'plot': 'A boy who communicates with spirits seeks the help of a disheartened child psychologist.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BMWM4NTFhYjctNzUyNi00NGMwLTk3NTYtMDIyNTZmMzRlYmQyXkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'},
   {'id': 14, 'genre': 'Thriller'},
   {'id': 15, 'genre': 'Mystery'}],
  'keywords': [{'id': 702, 'keyword': 'surprise ending'},
   {'id': 1115, 'keyword': 'ghost'},
   {'id': 1251, 'keyword': 'single mother'},
   {'id': 1252, 'keyword': 'able to see the dead'},
   {'id': 1253, 'keyword': 'plot twist'}]},
 {'imdb_id': 'tt0120907',
  'title': 'eXistenZ',
  'year': 1999,
  'popularity': 2394,
  'description': "Allegra Geller, the leading game designer in the world, is testing her new virtual reality game, eXistenZ with a focus group. As they begin, she is attacked by a fanatic assassin employing a bizarre organic gun. She flees with a young marketing trainee, Ted Pikul, who is suddenly assigned as her bodyguard. Unfortunately, her pod, an organic gaming device that contains the only copy of the eXistenZ game program, is damaged. To inspect it, she talks Ted into accepting a gameport in his own body so he can play the game with her. The events leading up to this, and the resulting game lead the pair on a strange adventure where reality and their actions are impossible to determine from either their own or the game's perspective.",
  'content_rating': 'R',
  'movie_length': 97,
  'rating': 6.8,
  'created_at': '2021-04-29T11:24:46.987501+03:00',
  'trailer': 'https://www.youtube.com/embed/HAdbdUt_h9M',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMmU1MTJkYWItMzM5Ny00NDgxLTgxOGEtNTkzNDdkZjkwNGI0XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-06-24',
  'plot': 'A game designer on the run from assassins must play her latest virtual reality creation with a marketing trainee to determine if the game has been damaged.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BMmU1MTJkYWItMzM5Ny00NDgxLTgxOGEtNTkzNDdkZjkwNGI0XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 11, 'genre': 'Sci-Fi'},
   {'id': 14, 'genre': 'Thriller'},
   {'id': 28, 'genre': 'Horror'}],
  'keywords': [{'id': 130, 'keyword': 'parallel world'},
   {'id': 871, 'keyword': 'game'},
   {'id': 2530, 'keyword': 'body horror'},
   {'id': 2551, 'keyword': 'alternate reality'},
   {'id': 8796, 'keyword': 'game designer'}]},
 {'imdb_id': 'tt0157503',
  'title': 'Drop Dead Gorgeous',
  'year': 1999,
  'popularity': 2405,
  'description': "In a small Minnesota town, the annual beauty pageant is being covered by a TV crew. Former winner Gladys Leeman wants to make sure her daughter follows in her footsteps. Explosions, falling lights, and trailer fires prove that. As the Leemans are the richest family in town the police are pretty relaxed about it all. Despite everything, main rival (but nice) Amber Atkins won't be stopped. There could well be more death and disappointment to come.",
  'content_rating': 'PG-13',
  'movie_length': 97,
  'rating': 6.6,
  'created_at': '2021-04-29T11:24:47.231850+03:00',
  'trailer': 'https://www.youtube.com/embed/dpkZV4wX92M',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BOTBhYjRlYmYtNzQxZS00NmEwLTk3OTAtNjU4MDEwMmUyZDczXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-06-08',
  'plot': 'A small-town beauty pageant turns deadly as it becomes clear that someone will go to any lengths to win.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BOTBhYjRlYmYtNzQxZS00NmEwLTk3OTAtNjU4MDEwMmUyZDczXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 9, 'genre': 'Comedy'},
   {'id': 14, 'genre': 'Thriller'},
   {'id': 26, 'genre': 'Romance'}],
  'keywords': [{'id': 96, 'keyword': 'murder'},
   {'id': 493, 'keyword': 'f rated'},
   {'id': 1394, 'keyword': 'small town'},
   {'id': 1460, 'keyword': 'beauty pageant'},
   {'id': 1867, 'keyword': 'minnesota'}]},
 {'imdb_id': 'tt0163651',
  'title': 'American Pie',
  'year': 1999,
  'popularity': 224,
  'description': 'Jim, Oz, Finch and Kevin are four friends who make a pact that before they graduate they will all lose their virginity. The hard job now is how to reach that goal by prom night. Whilst Oz begins singing to grab attention and Kevin tries to persuade his girlfriend, Finch tries any easy route of spreading rumors and Jim fails miserably. Whether it is being caught on top of a pie or on the Internet, Jim always ends up with his trusty sex advice from his father. Will they achieve their goal of getting laid by prom night? Or will they learn something much different?',
  'content_rating': 'R',
  'movie_length': 95,
  'rating': 7.0,
  'created_at': '2021-04-29T11:24:50.272722+03:00',
  'trailer': 'https://www.youtube.com/embed/iUZ3Yxok6N8',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMTg3ODY5ODI1NF5BMl5BanBnXkFtZTgwMTkxNTYxMTE@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-01-06',
  'plot': 'Four teenage boys enter a pact to lose their virginity by prom night.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BMTg3ODY5ODI1NF5BMl5BanBnXkFtZTgwMTkxNTYxMTE@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 9, 'genre': 'Comedy'}],
  'keywords': [{'id': 505, 'keyword': 'female frontal nudity'},
   {'id': 1301, 'keyword': 'nudity'},
   {'id': 1631, 'keyword': 'female masturbation'},
   {'id': 1632, 'keyword': 'prom'},
   {'id': 1633, 'keyword': 'milf'}]},
 {'imdb_id': 'tt0132347',
  'title': 'Mystery Men',
  'year': 1999,
  'popularity': 213,
  'description': "In order to generate more endorsement revenue, Champion City's resident superhero Captain Amazing arranges for the release of super villain Casanova Frankenstein, only to be captured by him. The city's fate rests in the hands of seven loser superhero wannabes: the fork-flinging Blue Rajah, the shovel-wielding Shoveler, the possessed bowling ball-hurling Bowler, the flatulent Spleen, the only-when-nobody's-looking Invisible Boy, the mysterious Sphinx, and the perpetually-angry Mr. Furious.",
  'content_rating': 'PG-13',
  'movie_length': 121,
  'rating': 6.1,
  'created_at': '2021-04-29T11:24:50.438280+03:00',
  'trailer': 'https://www.youtube.com/embed/weL-NjlIQ0E',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BYjdkZDRhYTgtNDliYS00ZmE1LThjYWMtOWNjNzNiODFmY2VmXkEyXkFqcGdeQXVyNjc4ODQwNzg@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-08-06',
  'plot': 'A group of inept amateur superheroes must try to save the day when a supervillain threatens to destroy a major superhero and the city.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BYjdkZDRhYTgtNDliYS00ZmE1LThjYWMtOWNjNzNiODFmY2VmXkEyXkFqcGdeQXVyNjc4ODQwNzg@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 6, 'genre': 'Fantasy'},
   {'id': 9, 'genre': 'Comedy'},
   {'id': 11, 'genre': 'Sci-Fi'},
   {'id': 13, 'genre': 'Action'}],
  'keywords': [{'id': 480, 'keyword': 'troubled production'},
   {'id': 845, 'keyword': 'action hero'},
   {'id': 846, 'keyword': 'retirement home'},
   {'id': 847, 'keyword': 'superhero spoof'},
   {'id': 848, 'keyword': 'bowling ball'}]},
 {'imdb_id': 'tt0177789',
  'title': 'Galaxy Quest',
  'year': 1999,
  'popularity': 587,
  'description': 'The sci-fi television series "Galaxy Quest", which took place aboard the intergalactic spaceship NSEA Protector, starred Jason Nesmith as suave Commander Peter Quincy Taggart, Gwen DeMarco as sexy communications person Lt. Tawny Madison (a role which consisted solely of repeating what the computer stated, much to Gwen\'s chagrin), Shakespearean trained Sir Alexander Dane as alien Dr. Lazarus, Fred Kwan as engineer Tech Sergeant Chen, and Tommy Webber as child pilot Laredo. Eighteen years after the series last aired, it lives on in the hearts of its rabid fans. However, it lives on in infamy for its stars, who have not been able to find meaningful acting work since. Their current lives revolve around cashing in on however those roles will afford, which usually entails attending fan conventions or worse, such as electronic store openings. Only Jason seems to relish his lot in life, until he finds out that his co-stars detest him because of his superior attitude as "the Commander", and ...',
  'content_rating': 'PG',
  'movie_length': 102,
  'rating': 7.3,
  'created_at': '2021-04-29T11:24:57.615101+03:00',
  'trailer': '',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BNmZlNTY5YjQtZTU5ZC00MzcyLWI1NDMtNjA0ZjQxMmQwYjJmL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-04-13',
  'plot': 'The alumni cast of a space opera television series have to play their roles as the real thing when an alien race needs their help. However, they also have to defend both Earth and the alien race from a reptilian warlord.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BNmZlNTY5YjQtZTU5ZC00MzcyLWI1NDMtNjA0ZjQxMmQwYjJmL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 9, 'genre': 'Comedy'},
   {'id': 11, 'genre': 'Sci-Fi'}],
  'keywords': [{'id': 366, 'keyword': 'alien'},
   {'id': 729, 'keyword': 'shapeshifting'},
   {'id': 1102, 'keyword': 'sexy woman'},
   {'id': 1103, 'keyword': 'actor'},
   {'id': 1104, 'keyword': 'fanboy'}]},
 {'imdb_id': 'tt0120915',
  'title': 'Star Wars: Episode I - The Phantom Menace',
  'year': 1999,
  'popularity': 608,
  'description': "The evil Trade Federation, led by Nute Gunray is planning to take over the peaceful world of Naboo. Jedi Knights Qui-Gon Jinn and Obi-Wan Kenobi are sent to confront the leaders. But not everything goes to plan. The two Jedi escape, and along with their new Gungan friend, Jar Jar Binks head to Naboo to warn Queen Amidala, but droids have already started to capture Naboo and the Queen is not safe there. Eventually, they land on Tatooine, where they become friends with a young boy known as Anakin Skywalker. Qui-Gon is curious about the boy, and sees a bright future for him. The group must now find a way of getting to Coruscant and to finally solve this trade dispute, but there is someone else hiding in the shadows. Are the Sith really extinct? Is the Queen really who she says she is? And what's so special about this young boy?",
  'content_rating': 'PG',
  'movie_length': 136,
  'rating': 6.5,
  'created_at': '2021-04-29T11:24:58.751065+03:00',
  'trailer': 'https://www.youtube.com/embed/bD7bpG-zDJQ',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BYTRhNjcwNWQtMGJmMi00NmQyLWE2YzItODVmMTdjNWI0ZDA2XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-09-30',
  'plot': 'Two Jedi escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to claim their original glory.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BYTRhNjcwNWQtMGJmMi00NmQyLWE2YzItODVmMTdjNWI0ZDA2XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 6, 'genre': 'Fantasy'},
   {'id': 11, 'genre': 'Sci-Fi'},
   {'id': 13, 'genre': 'Action'}],
  'keywords': [{'id': 628, 'keyword': 'slavery'},
   {'id': 1219, 'keyword': 'r2 d2 character'},
   {'id': 1220, 'keyword': 'c 3po character'},
   {'id': 1221, 'keyword': 'jedi'},
   {'id': 1222, 'keyword': 'torso cut in half'}]},
 {'imdb_id': 'tt0120655',
  'title': 'Dogma',
  'year': 1999,
  'popularity': 1966,
  'description': 'An abortion clinic worker with a special heritage is enlisted to prevent two angels from reentering Heaven and thus undoing the fabric of the universe. Along the way, she is aided by two prophets, Jay and Silent Bob. With the help of Rufus, the 13th Apostle, they must stop those who stand in their way and prevent the angels from entering Heaven.',
  'content_rating': 'R',
  'movie_length': 130,
  'rating': 7.3,
  'created_at': '2021-04-29T11:24:59.772540+03:00',
  'trailer': 'https://www.youtube.com/embed/20CRw3XdETA',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BYzAyOWUyZjQtNDBiMy00ZDExLTgwNmMtZDdmY2ViNzkyN2Y0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-08-03',
  'plot': 'An abortion clinic worker with a special heritage is called upon to save the existence of humanity from being negated by two renegade angels trying to exploit a loop-hole and reenter Heaven.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BYzAyOWUyZjQtNDBiMy00ZDExLTgwNmMtZDdmY2ViNzkyN2Y0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 6, 'genre': 'Fantasy'},
   {'id': 8, 'genre': 'Drama'},
   {'id': 9, 'genre': 'Comedy'}],
  'keywords': [{'id': 338, 'keyword': 'clinic'},
   {'id': 5064, 'keyword': 'silent bob character'},
   {'id': 5065, 'keyword': 'jay character'},
   {'id': 5066, 'keyword': 'angel'},
   {'id': 5069, 'keyword': 'abortion clinic'}]},
 {'imdb_id': 'tt0143145',
  'title': 'The World Is Not Enough',
  'year': 1999,
  'popularity': 1978,
  'description': "James Bond (Pierce Brosnan) is back. An oil tycoon is murdered in MI6, and Bond is sent to protect his daughter. Renard (Robert Carlyle), who has a bullet lodged in his brain from a previous Agent, is secretly planning the destruction of a pipeline. Bond gains a hand from research scientist Dr. Christmas Jones (Denise Richards), who witnesses the action which happens when Bond meets up with Renard, but Bond becomes suspicious about Elektra King (Sophie Marceau), especially when Bond's boss, M (Dame Judi Dench) goes missing. Bond must work quickly to prevent Renard from destroying Europe.",
  'content_rating': 'PG-13',
  'movie_length': 128,
  'rating': 6.4,
  'created_at': '2021-04-29T11:25:00.763884+03:00',
  'trailer': 'https://www.youtube.com/embed/9nH1DwQP2Xs',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMjA0MzUyNjg0MV5BMl5BanBnXkFtZTcwNDY5MDg0NA@@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-12-02',
  'plot': "James Bond uncovers a nuclear plot while protecting an oil heiress from her former kidnapper, an international terrorist who can't feel pain.",
  'banner': 'https://m.media-amazon.com/images/M/MV5BMjA0MzUyNjg0MV5BMl5BanBnXkFtZTcwNDY5MDg0NA@@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 7, 'genre': 'Crime'},
   {'id': 13, 'genre': 'Action'},
   {'id': 14, 'genre': 'Thriller'}],
  'keywords': [{'id': 1159, 'keyword': 'bare midriff'},
   {'id': 1701, 'keyword': 'official bond film'},
   {'id': 1956, 'keyword': 'black pantyhose'},
   {'id': 5667, 'keyword': 'female stockinged legs'},
   {'id': 6303, 'keyword': 'bilbao spain'}]},
 {'imdb_id': 'tt0145660',
  'title': 'Austin Powers: The Spy Who Shagged Me',
  'year': 1999,
  'popularity': 1969,
  'description': 'Dr. Evil uses a device he calls a "Time Machine" to travel back to 1969 and remove Austin Powers\' mojo. The sexually wounded swinger must travel back in time and, with the help of agent Felicity Shagwell, recover his vitality. Meanwhile, Dr. Evil\'s personal life runs amok as he discovers love, continues to shun his son and develops a close relationship with himself. Well, actually, a clone 1/8 his size whom he dubs "Mini-Me". The always time-baffled Dr. Evil begins his plan to put a gigantic cannon on the moon, thus turning it into a device called either "The Death Star" or "Alan Parson\'s Project," depending on which name is available.',
  'content_rating': 'PG-13',
  'movie_length': 95,
  'rating': 6.6,
  'created_at': '2021-04-29T11:25:00.824722+03:00',
  'trailer': 'https://www.youtube.com/embed/LGVjoLlgHbM',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMmFkZGQxN2YtODNlYS00MzM5LTk3NjQtNTUxYmQ1YzkwMDhmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-09-09',
  'plot': 'Dr. Evil is back and has invented a new time machine that allows him to go back to the 1960s and steal Austin Powers\' mojo, inadvertently leaving him "shagless".',
  'banner': 'https://m.media-amazon.com/images/M/MV5BMmFkZGQxN2YtODNlYS00MzM5LTk3NjQtNTUxYmQ1YzkwMDhmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 7, 'genre': 'Crime'},
   {'id': 9, 'genre': 'Comedy'},
   {'id': 13, 'genre': 'Action'}],
  'keywords': [{'id': 920, 'keyword': 'spy'},
   {'id': 1893, 'keyword': 'parody'},
   {'id': 4735, 'keyword': 'penis joke'},
   {'id': 4736, 'keyword': 'sexy agent'},
   {'id': 4737, 'keyword': 'sexual joke'}]},
 {'imdb_id': 'tt0149261',
  'title': 'Deep Blue Sea',
  'year': 1999,
  'popularity': 2012,
  'description': "A businessman sinks $200 million into a special project to help fight Alzheimer's disease. As part of this project, medical biologist Susan McAlester rather naughtily figures out a way to genetically enlarge shark brains, so that disease-battling enzymes can be harvested. However, the shark subjects become super smart and decide they don't much like being cooped up in pens and being stabbed with hypodermics, so they figure a way to break out and make for the open sea...",
  'content_rating': 'R',
  'movie_length': 105,
  'rating': 5.9,
  'created_at': '2021-04-29T11:25:02.348656+03:00',
  'trailer': 'https://www.youtube.com/embed/oSz9MDN-iac',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BZWM0NjVkOGYtMjk5Mi00NGVmLWE3NDMtMDQ3ZjdjMDcwYzdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-10-28',
  'plot': "Searching for a cure to Alzheimer's disease, a group of scientists on an isolated research facility become the prey, as a trio of intelligent sharks fight back.",
  'banner': 'https://m.media-amazon.com/images/M/MV5BZWM0NjVkOGYtMjk5Mi00NGVmLWE3NDMtMDQ3ZjdjMDcwYzdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 11, 'genre': 'Sci-Fi'},
   {'id': 13, 'genre': 'Action'},
   {'id': 14, 'genre': 'Thriller'}],
  'keywords': [{'id': 449, 'keyword': "alzheimer's disease"},
   {'id': 497, 'keyword': 'scientist'},
   {'id': 1194, 'keyword': 'shark'},
   {'id': 4011, 'keyword': 'experiment'},
   {'id': 5896, 'keyword': 'research'}]},
 {'imdb_id': 'tt0120363',
  'title': 'Toy Story 2',
  'year': 1999,
  'popularity': 2268,
  'description': 'While Andy is away at summer camp Woody has been toynapped by Al McWiggin, a greedy collector and proprietor of "Al\'s Toy Barn"! In this all-out rescue mission, Buzz and his friends Mr. Potato Head, Slinky Dog, Rex and Hamm springs into action to rescue Woody from winding up as a museum piece. They must find a way to save him before he gets sold in Japan forever and they\'ll never see him again!',
  'content_rating': 'G',
  'movie_length': 92,
  'rating': 7.9,
  'created_at': '2021-04-29T11:25:11.851780+03:00',
  'trailer': 'https://www.youtube.com/embed/xNWSGRD5CzU',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMWM5ZDcxMTYtNTEyNS00MDRkLWI3YTItNThmMGExMWY4NDIwXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-02-03',
  'plot': 'When Woody is stolen by a toy collector, Buzz and his friends set out on a rescue mission to save Woody before he becomes a museum toy property with his roundup gang Jessie, Prospector, and Bullseye.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BMWM5ZDcxMTYtNTEyNS00MDRkLWI3YTItNThmMGExMWY4NDIwXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 5, 'genre': 'Family'},
   {'id': 6, 'genre': 'Fantasy'},
   {'id': 9, 'genre': 'Comedy'},
   {'id': 10, 'genre': 'Animation'}],
  'keywords': [{'id': 47, 'keyword': 'rescue'},
   {'id': 483, 'keyword': 'cgi animation'},
   {'id': 1156, 'keyword': '1990s'},
   {'id': 2238, 'keyword': 'toy'},
   {'id': 2239, 'keyword': 'toy comes to life'}]},
 {'imdb_id': 'tt0120657',
  'title': 'The 13th Warrior',
  'year': 1999,
  'popularity': 2281,
  'description': 'A cultured diplomat joins a band of savage warriors in time to meet an even more fearsome enemy in this historical adventure. In 922 A.D., Ibn Fadlan (Antonio Banderas) is a Muslim emissary from Baghdad en route to meet with the King of Saqaliba when he is captured by a gang of Vikings. While Ibn and his people are intelligent and well-mannered, the Vikings are a rowdy and sometimes unpleasant lot, with an unquenchable appetite for food, alcohol, and women. However, in time he develops an understanding and respect for the Viking warriors and is welcomed into their society by their leader, Buliwyf. However, Ibn must now join them as they return to their homeland once they receive word of an invasion by a huge pack of bloodthirsty invaders who will destroy and eat anything in their path -- including the flesh of the men they have killed.',
  'content_rating': 'R',
  'movie_length': 102,
  'rating': 6.6,
  'created_at': '2021-04-29T11:25:13.035606+03:00',
  'trailer': 'https://www.youtube.com/embed/Ui7GUCzlBTM',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BNDZhZDk0ZTktZmNhMC00YTU1LWEwY2YtZmIyMWM5MTNlNDEwXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-10-07',
  'plot': 'A man, having fallen in love with the wrong woman, is sent by the sultan himself on a diplomatic mission to a distant land as an ambassador. Stopping at a Viking village port to restock on supplies, he finds himself unwittingly embroiled in a quest to banish a mysterious threat in a distant Viking land.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BNDZhZDk0ZTktZmNhMC00YTU1LWEwY2YtZmIyMWM5MTNlNDEwXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 13, 'genre': 'Action'},
   {'id': 31, 'genre': 'History'}],
  'keywords': [{'id': 482, 'keyword': 'warrior'},
   {'id': 554, 'keyword': 'battle'},
   {'id': 1157, 'keyword': 'combat'},
   {'id': 3953, 'keyword': 'viking'},
   {'id': 5594, 'keyword': 'arab'}]},
 {'imdb_id': 'tt0133093',
  'title': 'The Matrix',
  'year': 1999,
  'popularity': 155,
  'description': 'Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. As a rebel against the machines, Neo must confront the agents: super-powerful computer programs devoted to stopping Neo and the entire human rebellion.',
  'content_rating': 'R',
  'movie_length': 136,
  'rating': 8.7,
  'created_at': '2021-04-29T11:25:14.423635+03:00',
  'trailer': 'https://www.youtube.com/embed/vKQi3bBA1y8',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-06-17',
  'plot': 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 11, 'genre': 'Sci-Fi'}, {'id': 13, 'genre': 'Action'}],
  'keywords': [{'id': 114, 'keyword': 'post apocalypse'},
   {'id': 374, 'keyword': 'computer hacker'},
   {'id': 1591, 'keyword': 'simulated reality'},
   {'id': 1592, 'keyword': 'artificial reality'},
   {'id': 1593, 'keyword': 'war with machines'}]},
 {'imdb_id': 'tt0175880',
  'title': 'Magnolia',
  'year': 1999,
  'popularity': 950,
  'description': "24 hours in L.A.; it's raining cats and dogs. Two parallel and intercut stories dramatize men about to die: both are estranged from a grown child, both want to make contact, and neither child wants anything to do with dad. Earl Partridge's son is a charismatic misogynist; Jimmy Gator's daughter is a cokehead and waif. A mild and caring nurse intercedes for Earl, reaching the son; a prayerful and upright beat cop meets the daughter, is attracted to her, and leads her toward a new calm. Meanwhile, guilt consumes Earl's young wife, while two whiz kids, one grown and a loser and the other young and pressured, face their situations. The weather, too, is quirky.",
  'content_rating': 'R',
  'movie_length': 188,
  'rating': 8.0,
  'created_at': '2021-04-29T11:25:15.317562+03:00',
  'trailer': 'https://www.youtube.com/embed/KnamcFv_N9Q',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BZjk3YThkNDktNjZjMS00MTBiLTllNTAtYzkzMTU0N2QwYjJjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-04-13',
  'plot': 'An epic mosaic of interrelated characters in search of love, forgiveness, and meaning in the San Fernando Valley.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BZjk3YThkNDktNjZjMS00MTBiLTllNTAtYzkzMTU0N2QwYjJjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'}],
  'keywords': [{'id': 702, 'keyword': 'surprise ending'},
   {'id': 3987, 'keyword': 'cancer'},
   {'id': 5385, 'keyword': 'multiple storyline'},
   {'id': 7011, 'keyword': 'coincidence'},
   {'id': 7012, 'keyword': 'frog rain'}]},
 {'imdb_id': 'tt0120663',
  'title': 'Eyes Wide Shut',
  'year': 1999,
  'popularity': 376,
  'description': 'After his wife, Alice, tells him about her sexual fantasies, William Harford sets out for a night of sexual adventure. After several less than successful encounters, he meets an old friend, Nick Nightingale--now a musician--who tells him of strange sex parties where he is required to play the piano blindfolded. All the men at the party are costumed and wear masks while the women are all young and beautiful. Harford manages to find an appropriate costume and heads out to the party. Once there, however, he is warned by someone who recognizes him, despite the mask, that he is in great danger. He manages to extricate himself, but the threats prove to be quite real and sinister.',
  'content_rating': 'R',
  'movie_length': 159,
  'rating': 7.4,
  'created_at': '2021-04-29T11:25:21.057886+03:00',
  'trailer': 'https://www.youtube.com/embed/xgVo96JaqeM',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BN2ZhNjI5MGItMzMwZS00N2VhLWE2NTEtNjFmZmRiYzZlNGVmXkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-09-09',
  'plot': 'A New York City doctor embarks on a harrowing, night-long odyssey of sexual and moral discovery after his wife reveals a painful secret to him.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BN2ZhNjI5MGItMzMwZS00N2VhLWE2NTEtNjFmZmRiYzZlNGVmXkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'},
   {'id': 14, 'genre': 'Thriller'},
   {'id': 15, 'genre': 'Mystery'}],
  'keywords': [{'id': 1033, 'keyword': 'prostitute'},
   {'id': 2182, 'keyword': 'orgy'},
   {'id': 2183, 'keyword': 'password'},
   {'id': 2184, 'keyword': 'sex party'},
   {'id': 2185, 'keyword': 'sexual fantasy'}]},
 {'imdb_id': 'tt0120616',
  'title': 'The Mummy',
  'year': 1999,
  'popularity': 375,
  'description': "An English librarian called Evelyn Carnahan becomes interested in starting an archaeological dig at the ancient city of Hamunaptra. She gains the help of Rick O'Connell, after saving him from his death. What Evelyn, her brother Jonathan and Rick are unaware of is that another group of explorers are interested in the same dig. Unfortunately for everyone, this group ends up unleashing a curse which been laid on the dead High Priest Imhotep. Now 'The Mummy' is awake and it's going to take a lot more than guns to send him back to where he came from.",
  'content_rating': 'PG-13',
  'movie_length': 124,
  'rating': 7.0,
  'created_at': '2021-04-29T11:25:21.384980+03:00',
  'trailer': 'https://www.youtube.com/embed/f7oKxlaUBac',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BOTJiYjBhZDgtMjhiOC00MTIzLThlNGMtMmI1NjIwM2M3YTI5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-07-15',
  'plot': 'At an archaeological dig in the ancient city of Hamunaptra, an American serving in the French Foreign Legion accidentally awakens a mummy who begins to wreak havoc as he searches for the reincarnation of his long-lost love.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BOTJiYjBhZDgtMjhiOC00MTIzLThlNGMtMmI1NjIwM2M3YTI5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 6, 'genre': 'Fantasy'},
   {'id': 13, 'genre': 'Action'}],
  'keywords': [{'id': 1305, 'keyword': 'good versus evil'},
   {'id': 2145, 'keyword': 'mummy'},
   {'id': 2156, 'keyword': 'mummy character'},
   {'id': 2157, 'keyword': 'gallows'},
   {'id': 2158, 'keyword': '1920s'}]},
 {'imdb_id': 'tt0147800',
  'title': '10 Things I Hate About You',
  'year': 1999,
  'popularity': 397,
  'description': 'Adapted from William Shakespeare\'s play "The Taming of the Shrew," 10 Things I Hate About You starts off with Cameron, new student at Padua High, sitting in the office of the quirky guidance counselor Ms. Perky. He is then shown around the school by Michael, who will become his best friend. During his tour is when Cameron first sees Bianca Stratford, a beautiful sophomore with one problem: she isn\'t allowed to date. And neither is her "shrew" sister, Katarina, a senior who loves indie rock and feminist prose and hates conformity. But Kat and Bianca\'s father alters his house rule: now, Bianca can date... as long as Kat has a date, too. Now, in order for Cameron to date Bianca, he has to find someone to date Kat. So Michael helps him enlist the help of pretty-boy/jerk/model Joey Donner, tricking him into thinking that *he* will get to take Bianca out if he pays someone to take out Kat. His choice: Patrick Verona, a bad-boy with a mysterious reputation--some say he ate a live duck once, ...',
  'content_rating': 'PG-13',
  'movie_length': 97,
  'rating': 7.3,
  'created_at': '2021-04-29T11:25:21.775936+03:00',
  'trailer': 'https://www.youtube.com/embed/AWmjzCZr0Jw',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMmVhZjhlZDYtMDAwZi00MDcyLTgzOTItOWNiZjY0YmE0MGE0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-10-21',
  'plot': "A pretty, popular teenager can't go out on a date until her ill-tempered older sister does.",
  'banner': 'https://m.media-amazon.com/images/M/MV5BMmVhZjhlZDYtMDAwZi00MDcyLTgzOTItOWNiZjY0YmE0MGE0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'},
   {'id': 9, 'genre': 'Comedy'},
   {'id': 26, 'genre': 'Romance'}],
  'keywords': [{'id': 1017, 'keyword': 'protective father'},
   {'id': 1018, 'keyword': 'dating'},
   {'id': 1019, 'keyword': 'shakespeare adaptation'},
   {'id': 1020, 'keyword': 'high school shakespeare adaptation'},
   {'id': 20633, 'keyword': 'shrew'}]},
 {'imdb_id': 'tt0159097',
  'title': 'The Virgin Suicides',
  'year': 1999,
  'popularity': 1017,
  'description': "A man about forty years of age tells the story from when he was a teenager in upscale suburban Detroit of his and three of his friends' fascination with the mysterious and doomed Lisbon sisters. In 1974, the sisters were seventeen year old Therese, sixteen year old Mary, fifteen year old Bonnie, fourteen year old Lux, and thirteen year old Cecilia. Their fascination still remains as they try to piece together the entire story. The sisters were mysteries if only because of having a strict and overprotective upbringing by their father, who taught math at the girls' private co-ed school, and overly devout Catholic mother, who largely dictated the household rules. The story focuses primarily on two incidents and the resulting situations on the girls' lives. The first was an action by Cecilia to deal with her emotions over her life. And the second was the relationship between Lux - the sister who pushed the boundaries of the household rules most overtly in doing what most teenagers want to...",
  'content_rating': 'R',
  'movie_length': 97,
  'rating': 7.2,
  'created_at': '2021-04-29T11:25:25.223721+03:00',
  'trailer': 'https://www.youtube.com/embed/YRPXQ3XcpKc',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BNTMyMjI3MmItODIzNS00OWNiLWE5NTQtYmNhNGNlOTYyYWExXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-11-16',
  'plot': 'A group of male friends become obsessed with five mysterious sisters who are sheltered by their strict, religious parents in suburban Detroit in the mid 1970s.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BNTMyMjI3MmItODIzNS00OWNiLWE5NTQtYmNhNGNlOTYyYWExXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'}, {'id': 26, 'genre': 'Romance'}],
  'keywords': [{'id': 872, 'keyword': 'suicide'},
   {'id': 1501, 'keyword': '1970s'},
   {'id': 3659, 'keyword': 'catholic'},
   {'id': 6940, 'keyword': 'teen suicide'},
   {'id': 6941, 'keyword': 'overprotective parent'}]},
 {'imdb_id': 'tt0150377',
  'title': 'Double Jeopardy',
  'year': 1999,
  'popularity': 2031,
  'description': 'When Nick Parsons appears to be murdered his wife Libby is tried and convicted. Six years later Libby is paroled and is pursued by Travis Lehman (her parole officer) as she sets out to find her son and settle the score with Nick.',
  'content_rating': 'R',
  'movie_length': 105,
  'rating': 6.5,
  'created_at': '2021-04-29T11:25:27.456968+03:00',
  'trailer': 'https://www.youtube.com/embed/u22fy9OTaxo',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BM2UzNzYzMjctYmI0MS00MzQ3LTliMTktOTA1MGU0YTM3NzRjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-04-27',
  'plot': "A woman framed for her husband's murder suspects he is still alive; as she has already been tried for the crime, she can't be re-prosecuted if she finds and kills him.",
  'banner': 'https://m.media-amazon.com/images/M/MV5BM2UzNzYzMjctYmI0MS00MzQ3LTliMTktOTA1MGU0YTM3NzRjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 7, 'genre': 'Crime'},
   {'id': 8, 'genre': 'Drama'},
   {'id': 14, 'genre': 'Thriller'},
   {'id': 15, 'genre': 'Mystery'}],
  'keywords': [{'id': 600, 'keyword': 'wrongful conviction'},
   {'id': 719, 'keyword': 'sex scene'},
   {'id': 1024, 'keyword': 'blood'},
   {'id': 5245, 'keyword': 'wrongful arrest'},
   {'id': 5246, 'keyword': 'woman on top'}]},
 {'imdb_id': 'tt0235198',
  'title': 'Ôdishon',
  'year': 1999,
  'popularity': 1874,
  'description': 'In Tokyo, Shigeharu Aoyama is a widower that grieves the loss of his wife and raises his son Shigehiko Aoyama alone. Seven years later, the teenage Shigehiko asks why his middle-aged father does not remarry and Shigeharu meets his friend Yasuhisa Yoshikawa, who is a film producer, and tells his intention. However, Shigeharu has difficulties to approach to available women to date and Yasuhisa decide to organize a sham audition for casting the lead actress for the fake movie. They receive several portfolios of candidates and Shigeharu becomes obsessed by the gorgeous Asami Yamazaki. Despite the advice of the experienced Yasuhisa, Shigeharu calls Asami to date and he falls for her. But who is the mysterious Asami?',
  'content_rating': 'R',
  'movie_length': 115,
  'rating': 7.2,
  'created_at': '2021-04-29T11:25:30.965110+03:00',
  'trailer': 'aa.com',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BOWYzZjE4NzEtYzFhZS00Zjc3LWJjYTAtZjgwMGQyZjMxZjQ1XkEyXkFqcGdeQXVyNDQ5MDYzMTk@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-10-19',
  'plot': 'A widower takes an offer to screen girls at a special audition, arranged for him by a friend to find him a new wife. The one he fancies is not who she appears to be after all.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BOWYzZjE4NzEtYzFhZS00Zjc3LWJjYTAtZjgwMGQyZjMxZjQ1XkEyXkFqcGdeQXVyNDQ5MDYzMTk@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'},
   {'id': 15, 'genre': 'Mystery'},
   {'id': 28, 'genre': 'Horror'}],
  'keywords': [{'id': 362, 'keyword': 'torture'},
   {'id': 1301, 'keyword': 'nudity'},
   {'id': 1676, 'keyword': 'breasts'},
   {'id': 2146, 'keyword': 'blow job'},
   {'id': 9698, 'keyword': 'woman undressing'}]},
 {'imdb_id': 'tt0120604',
  'title': 'Beowulf',
  'year': 1999,
  'popularity': 1882,
  'description': "This post-apocalyptic future story is based on the 8th century Saxon epic poem about the knight who battled a monster in a medieval castle. In this story, Beowulf is a wanderer who learns about a man-eating creature called Grendel which comes in the night to devour warriors trapped at the Outpost. The Outpost is ruled by Hrothgar. He has a daughter, whose husband may have been murdered by the Outpost's master of arms.",
  'content_rating': 'R',
  'movie_length': 95,
  'rating': 4.2,
  'created_at': '2021-04-29T11:25:31.853320+03:00',
  'trailer': 'https://www.youtube.com/embed/BOrfinPSqyQ',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BZDk0N2Q5ZDktNWMyZC00NGI1LThmMWEtNTE3YjM0Nzg5YzAyXkEyXkFqcGdeQXVyNzA4ODc3ODU@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-04-01',
  'plot': 'In a besieged land, Beowulf must battle against the hideous creature Grendel and his vengeance seeking mother.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BZDk0N2Q5ZDktNWMyZC00NGI1LThmMWEtNTE3YjM0Nzg5YzAyXkEyXkFqcGdeQXVyNzA4ODc3ODU@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 6, 'genre': 'Fantasy'},
   {'id': 11, 'genre': 'Sci-Fi'},
   {'id': 13, 'genre': 'Action'},
   {'id': 14, 'genre': 'Thriller'},
   {'id': 28, 'genre': 'Horror'}],
  'keywords': [{'id': 442, 'keyword': 'monster'},
   {'id': 482, 'keyword': 'warrior'},
   {'id': 554, 'keyword': 'battle'},
   {'id': 606, 'keyword': 'knight'},
   {'id': 3132, 'keyword': 'sword and sorcery'}]},
 {'imdb_id': 'tt0185937',
  'title': 'The Blair Witch Project',
  'year': 1999,
  'popularity': 1802,
  'description': "In search of a local legend, three bold amateur documentarians--director, Heather; cameraman, Josh; sound recorder, Mike--hike into Burkittsville's gloomy Black Hills Forest to find a shadow: the fabled Blair Witch. Now, one long year later--after that fateful October of 1994--there's still no sign of the student filmmakers, apart from the raw footage they left behind. Who knows what truly happened during their creepy five-day journey into the mouth of madness? Was there, indeed, an intangible supernatural presence in the dark woods that led to the team's disappearance? Either way, the missing trio must have seen something. Could the nightmarish myth be real?",
  'content_rating': 'R',
  'movie_length': 81,
  'rating': 6.5,
  'created_at': '2021-04-29T11:25:35.771987+03:00',
  'trailer': 'https://www.youtube.com/embed/MBZ-POVsrlI',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BNzQ1NDBlNDItMDAyYS00YTI2LTgwMmYtMzAwMzg4NDFlM2ZmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-11-25',
  'plot': 'Three film students vanish after traveling into a Maryland forest to film a documentary on the local Blair Witch legend, leaving only their footage behind.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BNzQ1NDBlNDItMDAyYS00YTI2LTgwMmYtMzAwMzg4NDFlM2ZmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 15, 'genre': 'Mystery'}, {'id': 28, 'genre': 'Horror'}],
  'keywords': [{'id': 2796, 'keyword': 'lost in the woods'},
   {'id': 4545, 'keyword': 'maryland'},
   {'id': 4925, 'keyword': 'found footage'},
   {'id': 4926, 'keyword': 'supernatural horror'},
   {'id': 4927, 'keyword': 'ghost story'}]},
 {'imdb_id': 'tt0160862',
  'title': "She's All That",
  'year': 1999,
  'popularity': 831,
  'description': "She's All That is your typical high school prom king and queen story and the run in defending the star status in the upcoming election. High school hottie, Zack Siler is dumped by his prom-queen girlfriend, the equally attractive and extremely popular, Taylor Vaughan who fell for a second-hand world reject TV soap star who she met over the spring break. Having been publicly dumped, Zack defends his discomposure by stating that Taylor is all make-up and wonder-bra and he can make any ordinary girl a prom queen with a similar package. His high-school buddy, Dean Sampson, engages him in a bet following this statement and picks the geeky looking Laney Boggs out of the crowd as the girl Zack must transform into the new prom queen. Zack agrees since he has no option, but as time passes and Laney begins to transform, Zack begins to find her attractive. While all that falls beautifully in place, it's not your typical fairy-tale. Throw in Dean Sampson to complicate the situation, as when he ...",
  'content_rating': 'PG-13',
  'movie_length': 95,
  'rating': 5.9,
  'created_at': '2021-04-29T11:25:48.139633+03:00',
  'trailer': 'https://www.youtube.com/embed/cbvhImYUYQ4',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BY2Y0N2YyOTQtMGNiYy00ZDViLTgxYmItODkxNzlkMWVjNTFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-07-22',
  'plot': "A high school jock makes a bet that he can turn an unattractive girl into the school's prom queen.",
  'banner': 'https://m.media-amazon.com/images/M/MV5BY2Y0N2YyOTQtMGNiYy00ZDViLTgxYmItODkxNzlkMWVjNTFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 9, 'genre': 'Comedy'}, {'id': 26, 'genre': 'Romance'}],
  'keywords': [{'id': 163, 'keyword': 'bare chested male'},
   {'id': 273, 'keyword': 'male objectification'},
   {'id': 504, 'keyword': 'male nudity'},
   {'id': 2424, 'keyword': 'cinderella story'},
   {'id': 2425, 'keyword': 'claim in title'}]},
 {'imdb_id': 'tt0169547',
  'title': 'American Beauty',
  'year': 1999,
  'popularity': 335,
  'description': 'After his death sometime in his forty-third year, suburbanite Lester Burnham tells of the last few weeks of his life, during which he had no idea of his imminent passing. He is a husband to real estate agent Carolyn Burnham and father to high school student Janie Burnham. Although Lester and Carolyn once loved each other, they now merely tolerate each other. Typical wallflower Janie too hates both her parents, the three who suffer individually in silence in their home life. Janie tries to steer clear of both her parents. Carolyn, relatively new to the real estate business, wants to create the persona of success to further her career, she aspiring to the professional life of Buddy Kane, the king of the real estate business in their neighborhood. Lester merely walks mindlessly through life, including at his job in advertising. His company is downsizing, and he, like all the other employees, has to justify his position to the newly hired efficiency expert to keep his job. Things change ...',
  'content_rating': 'R',
  'movie_length': 122,
  'rating': 8.3,
  'created_at': '2021-04-29T11:25:52.179798+03:00',
  'trailer': 'https://www.youtube.com/embed/Ly7rq5EsTC8',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BNTBmZWJkNjctNDhiNC00MGE2LWEwOTctZTk5OGVhMWMyNmVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-01-20',
  'plot': "A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.",
  'banner': 'https://m.media-amazon.com/images/M/MV5BNTBmZWJkNjctNDhiNC00MGE2LWEwOTctZTk5OGVhMWMyNmVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'}],
  'keywords': [{'id': 197, 'keyword': 'cheating wife'},
   {'id': 198, 'keyword': 'adulterous wife'},
   {'id': 634, 'keyword': 'unfaithful wife'},
   {'id': 1675, 'keyword': 'midlife crisis'},
   {'id': 1676, 'keyword': 'breasts'}]},
 {'imdb_id': 'tt0172493',
  'title': 'Girl, Interrupted',
  'year': 1999,
  'popularity': 1169,
  'description': "In 1967, Susanna Kaysen had a headache and chased a bottle of aspirin with a bottle of vodka. This landed her in the mental institution, Claymoore. Here she is diagnosed, by Dr. Melvin Potts, with borderline personality disorder. When she arrives at Claymoore, she is greeted by Nurse Valerie Owens and shown round the woman's ward. Here she meets Georgina Tuskin, a pathological liar who is fixated with The Wizard of Oz; Polly Clark, a childlike schizophrenic; Janet Webber, a sardonic anorexic patient; Daisy Randone, a girl who won't let anyone in her room, and only eats her father's chicken; and Lisa Rowe, a sociopath who controls the other patients, and makes lives hard for the nurses at Claymoore. Through the movie, Lisa gains and loses control over Susanna and we see how bad she really can be. The movie's ending shows Susanna being released from Claymoore after an 18-month stay. How does Susanna take back her control? This movie battles subjects such as mental heath, abuse, ...",
  'content_rating': 'R',
  'movie_length': 127,
  'rating': 7.3,
  'created_at': '2021-04-29T11:25:57.200681+03:00',
  'trailer': 'https://www.youtube.com/embed/qHeqq6b6Vtw',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BNzdjZDYwM2QtMGNlZS00MGQzLTlhMjctYTU4NWI5MWJlYmQwXkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-06-08',
  'plot': "Based on writer Susanna Kaysen's account of her 18-month stay at a mental hospital in the late 1960s.",
  'banner': 'https://m.media-amazon.com/images/M/MV5BNzdjZDYwM2QtMGNlZS00MGQzLTlhMjctYTU4NWI5MWJlYmQwXkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'}, {'id': 27, 'genre': 'Biography'}],
  'keywords': [{'id': 124, 'keyword': 'based on true story'},
   {'id': 340, 'keyword': 'female protagonist'},
   {'id': 1432, 'keyword': 'borderline personality disorder'},
   {'id': 2739, 'keyword': 'mental institution'},
   {'id': 3671, 'keyword': 'mental hospital'}]},
 {'imdb_id': 'tt0185371',
  'title': 'House on Haunted Hill',
  'year': 1999,
  'popularity': 2834,
  'description': "An eccentric millionaire and his wife host a party in a haunted mansion for five strangers, who'll each be given $10,000 if they survive the night. A promotional stunt was created for its release in theatres, for which a plastic skeleton was flown over the audience during key moments of the film.",
  'content_rating': 'R',
  'movie_length': 93,
  'rating': 5.7,
  'created_at': '2021-04-29T11:26:23.499083+03:00',
  'trailer': 'https://www.youtube.com/embed/V-HA1Y5m2pY',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BNzUwYWQzZDQtMDQ0Mi00NjFlLTgzNjAtNTFhZmZhNWY4NGEzL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-05-25',
  'plot': 'An amusement park mogul offers a group of diverse people $1,000,000 to spend the night in a haunted house with a horrifying past.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BNzUwYWQzZDQtMDQ0Mi00NjFlLTgzNjAtNTFhZmZhNWY4NGEzL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 6, 'genre': 'Fantasy'},
   {'id': 7, 'genre': 'Crime'},
   {'id': 14, 'genre': 'Thriller'},
   {'id': 15, 'genre': 'Mystery'},
   {'id': 28, 'genre': 'Horror'}],
  'keywords': [{'id': 1676, 'keyword': 'breasts'},
   {'id': 2026, 'keyword': 'haunted house'},
   {'id': 6246, 'keyword': 'characters killed one by one'},
   {'id': 8687, 'keyword': 'haunted hospital'},
   {'id': 8688, 'keyword': 'strapped to a bed'}]},
 {'imdb_id': 'tt0123964',
  'title': 'Life',
  'year': 1999,
  'popularity': 2851,
  'description': "In the mid-1990s, two inmates bury the burned bodies of two lifers at Mississippi's infamous Parchman Farm; a third old-timer relates their story. They'd served 65 years for a murder they didn't commit, framed by a local sheriff while buying moonshine whiskey for a Manhattan club owner to whom they owed money. In flashbacks we see this odd couple thrown together (Ray is a fast-talking con man, and Claude is a serious man about to start work as a bank teller), the loss of Ray's watch (sterling silver, from his daddy), the murder and trial, the hardships of Parchman, and the love-hate relationship of Claude and Ray as they spend 65 years bickering and looking for a way to escape.",
  'content_rating': 'R',
  'movie_length': 108,
  'rating': 6.8,
  'created_at': '2021-04-29T11:26:23.842751+03:00',
  'trailer': 'https://www.youtube.com/embed/7R_vTEEyxoo',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BN2M0YWM1OTgtMDY1Ni00Y2RkLTkxNzktODUyNDU0YWFkYjQyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-06-01',
  'plot': 'In 1932, two strangers are wrongfully convicted and develop a strong friendship in prison that lasts them through the 20th century.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BN2M0YWM1OTgtMDY1Ni00Y2RkLTkxNzktODUyNDU0YWFkYjQyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 7, 'genre': 'Crime'},
   {'id': 8, 'genre': 'Drama'},
   {'id': 9, 'genre': 'Comedy'}],
  'keywords': [{'id': 37, 'keyword': 'wrongful imprisonment'},
   {'id': 600, 'keyword': 'wrongful conviction'},
   {'id': 1822, 'keyword': 'baseball'},
   {'id': 9402, 'keyword': 'year 1932'},
   {'id': 9403, 'keyword': 'passage of time'}]},
 {'imdb_id': 'tt0132477',
  'title': 'October Sky',
  'year': 1999,
  'popularity': 2712,
  'description': "In a 1950's mining town called Coalwood, Homer Hickam is a kid with only one future in sight, to work in the local coal mine like his father. However in October 1957, everything changes when the first artificial satellite, Sputnik goes into orbit. With that event, Homer becomes inspired to learn how to build rockets. With his friends and the local nerd, Homer sets to do just that by trial and a lot of error. Unfortunately, most of the town and especially Homer's father thinks that they are wasting their time. Only one teacher in the high school understands their efforts and lets them know that they could become contenders in the national science fair with college scholarships being the prize. Now the gang must learn to perfect their craft and overcome the many problems facing them as they shoot for the stars.",
  'content_rating': 'PG',
  'movie_length': 108,
  'rating': 7.8,
  'created_at': '2021-04-29T11:26:24.020009+03:00',
  'trailer': 'https://www.youtube.com/embed/zxJQgYPXjN4',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BZmIzMjE0M2YtNzliZi00YWNmLTgyNDItZDhjNWVhY2Q2ODk0XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-02-19',
  'plot': "The true story of Homer Hickam, a coal miner's son who was inspired by the first Sputnik launch to take up rocketry against his father's wishes.",
  'banner': 'https://m.media-amazon.com/images/M/MV5BZmIzMjE0M2YtNzliZi00YWNmLTgyNDItZDhjNWVhY2Q2ODk0XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 5, 'genre': 'Family'},
   {'id': 8, 'genre': 'Drama'},
   {'id': 27, 'genre': 'Biography'}],
  'keywords': [{'id': 231, 'keyword': 'nerd'},
   {'id': 536, 'keyword': 'hope'},
   {'id': 2952, 'keyword': 'competition'},
   {'id': 6364, 'keyword': 'alcohol'},
   {'id': 8011, 'keyword': 'rocket'}]},
 {'imdb_id': 'tt0124315',
  'title': 'The Cider House Rules',
  'year': 1999,
  'popularity': 3712,
  'description': "Homer is an orphan in remote St. Cloud, Maine. Never adopted, he becomes the favorite of orphanage Director Dr. Larch, who imparts his full medical knowledge on Homer, who becomes a skilled, albeit unlicensed, physician. But Homer yearns for a self-chosen life outside the orphanage. When Wally and pregnant Candy visit the orphanage, Dr. Larch provides a medically safe, albeit illegal, abortion, Homer leaves with them to work on Wally's family apple farm. Wally goes off to war, leaving Homer and Candy alone together. What will Homer learn about life and love in the cider house? What of the destiny that Dr. Larch has planned for him?",
  'content_rating': 'PG-13',
  'movie_length': 126,
  'rating': 7.4,
  'created_at': '2021-04-29T11:26:31.546605+03:00',
  'trailer': 'https://www.youtube.com/embed/pGdZBESUSfk',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BNmY5YzA4OTQtOTQzZS00NDZmLTlhNzQtNzk5NTIyZWE2ZjVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-03-16',
  'plot': 'A compassionate young man, raised in an orphanage and trained to be a doctor there, decides to leave to see the world.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BNmY5YzA4OTQtOTQzZS00NDZmLTlhNzQtNzk5NTIyZWE2ZjVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'}, {'id': 26, 'genre': 'Romance'}],
  'keywords': [{'id': 506, 'keyword': 'female nudity'},
   {'id': 630, 'keyword': 'racism'},
   {'id': 719, 'keyword': 'sex scene'},
   {'id': 1568, 'keyword': 'premarital sex'},
   {'id': 10042, 'keyword': 'woman dies from abortion'}]},
 {'imdb_id': 'tt0124298',
  'title': 'Blast from the Past',
  'year': 1999,
  'popularity': 3729,
  'description': 'Adam Weber is the child of an eccentric inventor and his wife. Following a bomb scare in the 1960s that locked the Webers in their bomb shelter for 35 years, Adam Weber must venture out into Los Angeles and obtain food and supplies for his family. He meets Eve, who reluctantly agrees to help him out.',
  'content_rating': 'PG-13',
  'movie_length': 112,
  'rating': 6.6,
  'created_at': '2021-04-29T11:26:32.114827+03:00',
  'trailer': 'https://www.youtube.com/embed/AhMQOb0tEmI',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BZGFiZjRhMTYtZmMzYS00MGEyLWEzN2EtNWMzMjA3OGI0NGZlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-09-23',
  'plot': 'A naive man comes out into the world after spending 35 years in a nuclear fallout shelter.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BZGFiZjRhMTYtZmMzYS00MGEyLWEzN2EtNWMzMjA3OGI0NGZlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'},
   {'id': 9, 'genre': 'Comedy'},
   {'id': 11, 'genre': 'Sci-Fi'},
   {'id': 26, 'genre': 'Romance'}],
  'keywords': [{'id': 245, 'keyword': 'friendship'},
   {'id': 1465, 'keyword': 'united states'},
   {'id': 1466, 'keyword': 'usa'},
   {'id': 5345, 'keyword': 'falling in love'},
   {'id': 8217, 'keyword': 'bomb shelter'}]},
 {'imdb_id': 'tt0120188',
  'title': 'Three Kings',
  'year': 1999,
  'popularity': 3715,
  'description': 'A small group of adventurous American soldiers in Iraq at the end of the Gulf War are determined to steal a huge cache of gold reputed to be hidden somewhere near their desert base. Finding a map they believe will take them to the gold, they embark on a journey that leads to unexpected discoveries, enabling them to rise to a heroic challenge that drastically changes their lives.',
  'content_rating': 'R',
  'movie_length': 114,
  'rating': 7.1,
  'created_at': '2021-04-29T11:26:32.489905+03:00',
  'trailer': 'https://www.youtube.com/embed/OyR5bk4_pHk',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BZjQ5MzM1ZGItZDQyYi00ZDQ5LWJkMDQtYTIxZmIwNWQ5NmUxL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-03-02',
  'plot': 'In the aftermath of the Persian Gulf War, four soldiers set out to steal gold that was stolen from Kuwait, but they discover people who desperately need their help.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BZjQ5MzM1ZGItZDQyYi00ZDQ5LWJkMDQtYTIxZmIwNWQ5NmUxL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 8, 'genre': 'Drama'},
   {'id': 9, 'genre': 'Comedy'},
   {'id': 13, 'genre': 'Action'},
   {'id': 29, 'genre': 'War'}],
  'keywords': [{'id': 430, 'keyword': 'heist'},
   {'id': 1380, 'keyword': 'original story'},
   {'id': 5246, 'keyword': 'woman on top'},
   {'id': 7470, 'keyword': 'cell phone trace'},
   {'id': 7977, 'keyword': 'sex on a chair'}]},
 {'imdb_id': 'tt0129167',
  'title': 'The Iron Giant',
  'year': 1999,
  'popularity': 2317,
  'description': "This is the story of a nine-year-old boy named Hogarth Hughes who makes friends with an innocent alien giant robot that came from outer space. Meanwhile, a paranoid U.S. Government agent named Kent Mansley arrives in town, determined to destroy the giant at all costs. It's up to Hogarth to protect him by keeping him at Dean McCoppin's place in the junkyard.",
  'content_rating': 'PG',
  'movie_length': 86,
  'rating': 8.0,
  'created_at': '2021-04-29T11:26:38.149030+03:00',
  'trailer': 'https://www.youtube.com/embed/doSJxiYp9yo',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMjIxNDU2Njk0OV5BMl5BanBnXkFtZTgwODc3Njc3NjE@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-12-16',
  'plot': 'A young boy befriends a giant robot from outer space that a paranoid government agent wants to destroy.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BMjIxNDU2Njk0OV5BMl5BanBnXkFtZTgwODc3Njc3NjE@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 5, 'genre': 'Family'},
   {'id': 8, 'genre': 'Drama'},
   {'id': 9, 'genre': 'Comedy'},
   {'id': 10, 'genre': 'Animation'},
   {'id': 11, 'genre': 'Sci-Fi'},
   {'id': 13, 'genre': 'Action'}],
  'keywords': [{'id': 232, 'keyword': 'friend'},
   {'id': 245, 'keyword': 'friendship'},
   {'id': 331, 'keyword': 'robot'},
   {'id': 1674, 'keyword': 'cult film'},
   {'id': 2612, 'keyword': 'government agent'}]},
 {'imdb_id': 'tt0171363',
  'title': 'The Haunting',
  'year': 1999,
  'popularity': 3017,
  'description': 'A remake of the classic 1963 movie "The Haunting" about a team of paranormal experts who look into strange occurrences in an ill-fated house. Through the course of the night some will unravel, some will question, and all will fight for their lives as the house fights back.',
  'content_rating': 'PG-13',
  'movie_length': 113,
  'rating': 5.0,
  'created_at': '2021-04-29T11:26:39.586112+03:00',
  'trailer': 'https://www.youtube.com/embed/J4fWI5J4bEU',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BMzBhMThiM2YtMWQ1OS00NmMyLWI4NGMtMjE3YzBmMTBiODJhL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-10-14',
  'plot': 'A study in fear escalates into a heart-stopping nightmare for a professor and three subjects trapped in a mysterious mansion.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BMzBhMThiM2YtMWQ1OS00NmMyLWI4NGMtMjE3YzBmMTBiODJhL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 6, 'genre': 'Fantasy'},
   {'id': 14, 'genre': 'Thriller'},
   {'id': 15, 'genre': 'Mystery'},
   {'id': 28, 'genre': 'Horror'}],
  'keywords': [{'id': 1635, 'keyword': 'horror movie remake'},
   {'id': 2026, 'keyword': 'haunted house'},
   {'id': 2982, 'keyword': 'mansion'},
   {'id': 5738, 'keyword': 'old house'},
   {'id': 8235, 'keyword': 'insomniac'}]},
 {'imdb_id': 'tt0120891',
  'title': 'Wild Wild West',
  'year': 1999,
  'popularity': 2654,
  'description': 'Jim West is a guns-a-blazing former Civil War hero. Artemus Gordon is an inventive U.S. Marshal who excels in disguise. When the United States is threatened by psychotic Confederate Arliss Loveless, President Ulysses S Grant teams the duo up to bring him to justice. On a hazard-packed train journey from Washington, D.C. to Utah, West and Gordon must combine their skills to best Loveless and his diabolical machines.',
  'content_rating': 'PG-13',
  'movie_length': 106,
  'rating': 5.0,
  'created_at': '2021-04-29T11:26:42.985654+03:00',
  'trailer': 'https://www.youtube.com/embed/It89i3W-v4s',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BYmYyMTc4YjItMGNhNC00OWQwLWJhMWUtNTdjZDgxMDI5MjE2L2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-07-29',
  'plot': 'The two best special agents in the Wild West must save President Grant from the clutches of a diabolical, wheelchair-bound, steampunk-savvy, Confederate scientist bent on revenge for losing the Civil War.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BYmYyMTc4YjItMGNhNC00OWQwLWJhMWUtNTdjZDgxMDI5MjE2L2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 9, 'genre': 'Comedy'},
   {'id': 11, 'genre': 'Sci-Fi'},
   {'id': 13, 'genre': 'Action'},
   {'id': 25, 'genre': 'Western'}],
  'keywords': [{'id': 1057, 'keyword': 'ulysses s. grant character'},
   {'id': 1426, 'keyword': 'steampunk'},
   {'id': 2532, 'keyword': 'buddy movie'},
   {'id': 2622, 'keyword': 'george washington character'},
   {'id': 10089, 'keyword': 'utah'}]},
 {'imdb_id': 'tt0144117',
  'title': 'The Boondock Saints',
  'year': 1999,
  'popularity': 1607,
  'description': 'Two Irish brothers accidentally kill mafia thugs. They turn themselves in and are released as heroes. They then see it as a calling by God and start knocking off mafia gang members one by one. Willem Dafoe plays the detective trying to figure out the killings, but the closer he comes to catching the Irish brothers, the more he thinks the brothers are doing the right thing.',
  'content_rating': 'R',
  'movie_length': 108,
  'rating': 7.8,
  'created_at': '2021-04-29T11:26:46.273722+03:00',
  'trailer': 'https://www.youtube.com/embed/ydXojYfCF3I',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BYzVmMTdjOTYtOTJkYS00ZTg2LWExNTgtNzA1N2Y0MDgwYWFhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-01-21',
  'plot': "Two Irish Catholic brothers become vigilantes and wipe out Boston's criminal underworld in the name of God.",
  'banner': 'https://m.media-amazon.com/images/M/MV5BYzVmMTdjOTYtOTJkYS00ZTg2LWExNTgtNzA1N2Y0MDgwYWFhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 7, 'genre': 'Crime'},
   {'id': 13, 'genre': 'Action'},
   {'id': 14, 'genre': 'Thriller'}],
  'keywords': [{'id': 13, 'keyword': 'drinking'},
   {'id': 1090, 'keyword': 'male male kiss'},
   {'id': 1461, 'keyword': 'gay'},
   {'id': 4806, 'keyword': 'gay slur'},
   {'id': 4807, 'keyword': 'cauterizing a wound'}]},
 {'imdb_id': 'tt0120855',
  'title': 'Tarzan',
  'year': 1999,
  'popularity': 1625,
  'description': "The movie is about the life of Tarzan. Tarzan was a small orphan who was raised by an ape named Kala since he was a child. He believed that this was his family, but on an expedition Jane Porter is rescued by Tarzan. He then finds out that he's human. Now Tarzan must make the decision as to which family he should belong to...",
  'content_rating': 'G',
  'movie_length': 88,
  'rating': 7.3,
  'created_at': '2021-04-29T11:26:47.698576+03:00',
  'trailer': 'https://www.youtube.com/embed/MwU5ZqyhV5Q',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BY2ZiYWUxN2ItYmQxZi00NDlkLWE2NDAtOTNmYTg1MDI0NDk1XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-11-18',
  'plot': 'A man raised by gorillas must decide where he really belongs when he discovers he is a human.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BY2ZiYWUxN2ItYmQxZi00NDlkLWE2NDAtOTNmYTg1MDI0NDk1XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 4, 'genre': 'Adventure'},
   {'id': 5, 'genre': 'Family'},
   {'id': 10, 'genre': 'Animation'}],
  'keywords': [{'id': 1162, 'keyword': 'africa'},
   {'id': 1305, 'keyword': 'good versus evil'},
   {'id': 2855, 'keyword': 'death of parents'},
   {'id': 4909, 'keyword': 'tarzan character'},
   {'id': 4910, 'keyword': 'baboon'}]},
 {'imdb_id': 'tt0179116',
  'title': "But I'm a Cheerleader",
  'year': 1999,
  'popularity': 1657,
  'description': 'Megan is an all-American girl. She\'s a cheerleader and has a boyfriend, but she doesn\'t like kissing him very much, and she\'s pretty tactile with her cheerleader friends, and she only has pictures of girls up in her locker. Her parents and friends conclude that she *must* be gay and send her off to "sexual redirection" school, full of admittedly homosexual misfits, where she can learn how to be straight. Will Megan be turned around to successful heterosexuality, or will she succumb to her love for the beautiful Graham?',
  'content_rating': 'R',
  'movie_length': 85,
  'rating': 6.7,
  'created_at': '2021-04-29T11:26:50.052365+03:00',
  'trailer': 'https://www.youtube.com/embed/YxxaLMGi9ng',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BNmZjNGVmYmItZWFmNi00ODQ1LThmZTUtMzYzMGJlMjZjMGFiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '2000-12-21',
  'plot': 'A naive teenager is sent to rehab camp when her straitlaced parents and friends suspect her of being a lesbian.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BNmZjNGVmYmItZWFmNi00ODQ1LThmZTUtMzYzMGJlMjZjMGFiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 8, 'genre': 'Drama'},
   {'id': 9, 'genre': 'Comedy'},
   {'id': 26, 'genre': 'Romance'}],
  'keywords': [{'id': 458, 'keyword': 'lesbian kiss'},
   {'id': 548, 'keyword': 'lesbian relationship'},
   {'id': 1359, 'keyword': 'lesbian'},
   {'id': 1679, 'keyword': 'cheerleader'},
   {'id': 1892, 'keyword': 'lesbian teen'}]},
 {'imdb_id': 'tt0155776',
  'title': 'Jawbreaker',
  'year': 1999,
  'popularity': 3265,
  'description': "In a no-holds-barred birthday prank, three of Reagan High School's most popular girls - Julie, Marcie, and Courtney - pretend to kidnap the most popular, Liz Purr. Courtney shoves a jawbreaker into the victim's mouth ostensibly to keep her from screaming. Their plan goes awry when the girl accidentally swallows the jawbreaker, choking to death. The cool and calculating Courtney tries to cover the crime but is found out by school geek Fern Mayo. In return for her silence, Courtney transforms the gawky Fern into the stylishly beautiful Vylette, leaving the conscience-stricken Julie out in the cold, threatening to set her up for the girl's murder if she breaks her silence.",
  'content_rating': 'R',
  'movie_length': 87,
  'rating': 5.7,
  'created_at': '2021-04-29T11:26:57.519672+03:00',
  'trailer': 'https://www.youtube.com/embed/bnroZaiPMy8',
  'image_url': 'https://m.media-amazon.com/images/M/MV5BOTcwZWZkZWUtZjRhMi00ZDNhLTljOWItNjBkNzIwYTA0YWQyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg',
  'release': '1999-02-19',
  'plot': 'Three of the most popular girls at Reagan High accidentally kill the prom queen with a jawbreaker when a kidnapping goes horribly wrong.',
  'banner': 'https://m.media-amazon.com/images/M/MV5BOTcwZWZkZWUtZjRhMi00ZDNhLTljOWItNjBkNzIwYTA0YWQyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
  'type': 'movie',
  'more_like_this': {},
  'gen': [{'id': 7, 'genre': 'Crime'},
   {'id': 9, 'genre': 'Comedy'},
   {'id': 14, 'genre': 'Thriller'}],
  'keywords': [{'id': 132, 'keyword': 'written by director'},
   {'id': 340, 'keyword': 'female protagonist'},
   {'id': 1328, 'keyword': 'erotica'},
   {'id': 7525, 'keyword': 'popsicle'},
   {'id': 7526, 'keyword': 'fake kidnapping'}]}]